### ISSUE TITLE
prettier.resolveConfig.sync is not a function

### ISSUE THREAD

**Issue by kamalkech** [prettier/pretty-quick#168] opened 2023-09-13 20:16 UTC
any idea how to fixe this issue ??
```
TypeError: _prettier.resolveConfig.sync is not a function
    at /my-project/node_modules/.pnpm/pretty-quick@3.1.3_prettier@3.0.3/node_mo
dules/pretty-quick/dist/isSupportedExtension.js:12:30
    at Array.filter (<anonymous>)
    at _default (/my-project/node_modules/.pnpm/pretty-quick@3.1.3_prettier@3.0
.3/node_modules/pretty-quick/dist/index.js:53:157)
```

**Comment by blimmer** [comment] 2023-09-14 15:05
See #164 - I've been moving to lint-staged

**Comment by kasir-barati** [comment] 2023-12-20 18:24
Same here. My packages version:
```
"@types/jest": "^29.5.11",
"@typescript-eslint/eslint-plugin": "^6.15.0",
"@typescript-eslint/parser": "^6.15.0",
"eslint": "^8.56.0",
"eslint-config-prettier": "^9.1.0",
"eslint-plugin-jest": "^27.6.0",
"eslint-plugin-prettier": "^5.1.0",
"eslint-plugin-unused-imports": "^3.0.0",
"husky": "^8.0.3",
"jest": "^29.7.0",
"prettier": "^3.1.1",
"pretty-quick": "^3.1.3",
"ts-jest": "^29.1.1",
"typescript": "^5.3.3"
```

**Comment by NivEz** [comment] 2023-12-28 18:01
@kasir-barati I use `"pretty-quick": "^2.8.0"` altough it's older and it works for me.

**Comment by JounQin** [comment] 2024-01-15 07:54
Duplicate of #164

**Closed by JounQin** 2024-01-15 07:54 UTC

**Comment by kasir-barati** [comment] 2024-01-15 07:59
@NivEz I really do not wanna like to downgrade it unless there is a strong reason -- something like old codebase, tight deadlines that won't leave room for other kind of stuff.

but under normal circumstances I would prefer to stick to the latest changes as much as possible
